config/routes.rb
Diddleberry::Application.routes.draw do
  root to: 'Users#show'
  resources :users, only: [:edit, :update]
  resources :emails, only: [:create]
  resources :log_in_requests, only: [:new, :create]
  get "/e/:token" => 'UserSessions#create', as: :user_sessions
  get "/e/:token/remove" => 'emails#destroy', as: :remove_email
  get '/check_email' => 'Pages#check_email'
  get '/log_out' => 'UserSessions#destroy'
  get '/me/edit' => 'Users#edit', as: :edit_me
end

app/models/concerns/delete_protection.rb
module DeleteProtection
  extend ActiveSupport::Concern

  included do
    before_destroy ->(record){ record.deleteable? }
  end

  def deleteable?
    true
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  include DeleteProtection

  belongs_to :user
  validates :address, presence: true, uniqueness: true
  before_validation :set_token, on: :create

  def confirmed?
    confirmed_at?
  end

  def confirm!
    touch(:confirmed_at) unless confirmed?
  end

  def deleteable?
    user.emails.count > 1
  end

  private

  def set_token
    self.token = SecureRandom.hex[0, 10]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :emails, dependent: :destroy

  def self.from_email(address)
    if email = Email.find_by_address(address)
      [ email.user, email ]
    else
      user = create
      email = user.emails.create(address: address)
      [ user, email ]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authorize
    redirect_to new_log_in_request_path unless logged_in?
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def new
  end

  def create
    @user, @email = *User.from_email(params[:email])
    if @user.valid?
      SuckerPunch::Queue[:emails].async.perform(@email)
      session[:email] = @email.address
      redirect_to check_email_url
    else
      render :new
    end
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
    @email = current_user.emails.new(email_params)

    if @email.save
      SuckerPunch::Queue[:emails].async.perform(:confirm_email, @email)
      flash[:notice] = "Please check #{@email.address} for a link to confirm the email address. "
      redirect_to root_url
    else
      flash[:error] = "That address is invalid. Please try entering a valid email address. "
      redirect_to root_url
    end
  end

  def destroy
    email = current_user.emails.find_by_token(params[:token])
    email.destroy
    redirect_to root_url, notice: "#{email.address} has been removed from your account."
  end

  private
  def email_params
    params.require(:email).permit(:address)
  end
end

app/controllers/log_in_requests_controller.rb
class LogInRequestsController < ApplicationController
  def new
  end

  def create
    @user, @email = *User.from_email(params[:email])
    if @user.valid?
      SuckerPunch::Queue[:emails].async.perform(:log_in_request, @email)
      session[:email] = @email.address
      redirect_to check_email_url
    else
      render :new
    end
  end
end

app/controllers/login_requests_controller.rb
class LoginRequestsController < ApplicationController
  def new
  end

  def create
    @user, @email = *User.from_email(params[:email])
    if @user.valid?
      SuckerPunch::Queue[:emails].async.perform(:log_in_request, @email)
      session[:email] = @email.address
      redirect_to check_email_url
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def check_email
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def create
    @email = Email.find_by_token!(params[:token])
    @email.confirm!
    session[:user_id] = @email.user.id
    if current_user.name?
      redirect_to root_url
    else
      redirect_to edit_me_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize

  def show
  end

  def edit
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Made by:
#Colossal
       .d8888b.   .d8888b.
      d88P  Y88b d88P  Y88b
           .d88P Y88b. d88P
888d888   8888"   "Y88888"  888  888
888P"      "Y8b. .d8P""Y8b. 888  888
888   888    888 888    888 888  888
888   Y88b  d88P Y88b  d88P Y88b 888
888    "Y8888P"   "Y8888P"   "Y88888
                                 888
                            Y8b d88P
                             "Y88P"
#roman
           .oooo.    .ooooo.
         .dP""Y88b  d88'   `8.
oooo d8b       ]8P' Y88..  .8' oooo    ooo
`888""8P     <88b.   `88888b.   `88.  .8'
 888          `88b. .8'  ``88b   `88..8'
 888     o.   .88P  `8.   .88P    `888'
d888b    `8bd88P'    `boood8'      .8'
                               .o..P'
                               `Y8P'
-->
<html>
<head>
  <title>Diddleberry</title>
  <%# <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">%>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="span4 offset4">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
  <%= javascript_include_tag :application %>
</body>
</html>

app/views/log_in_requests/new.html.haml
= form_tag log_in_requests_path, class: 'form-inline' do
  %div.input-append
    = text_field_tag :email, '', autofocus: true, placeholder: 'Your email address'
    = button_tag "Submit", type: 'submit', class: 'btn btn-primary'

app/views/login_requests/new.html.haml
= form_tag login_requests_path, class: 'form-inline' do
  %div.input-append
    = text_field_tag :email, '', autofocus: true, placeholder: 'Your email address'
    = button_tag "Submit", type: 'submit', class: 'btn btn-primary'

app/views/notifier/confirm_email.html.haml
%p Hi there,

%p Please click the following link to confirm adding #{@email.address} to your account:

%p=link_to user_sessions_url(@email.token), user_sessions_url(@email.token)

%p Thank you!

app/views/notifier/log_in_request.html.haml
%p Hi there,

%p Please click on the URL below to finish logging into Diddleberry:

%p=link_to user_sessions_url(@email.token), user_sessions_url(@email.token)

%p Thank you!

app/views/pages/check_email.html.haml
%div.alert.alert-success.alert-block
  %h4 Check your email!
  %p Please check <strong>#{session[:email]}</strong> for a link to log in.
  %p Didn't get an email? #{link_to "Try again", new_log_in_request_path}.

app/views/shared/_flashes.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% if flash[level].present?%>
    <div class="alert alert-<%= flash_class(level) %>">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= flash[level]%>
    </div>
  <% end%>
<% end %>

app/views/users/edit.html.haml
= form_for current_user, html: { class: 'form-inline' } do |f|
  %div.input-append
    = f.text_field :name, autofocus: true, placeholder: 'What should we call you?'
    = f.button "Submit", class: 'btn btn-primary'

app/views/users/show.html.haml
%h4
  = current_user.name

%ul{class: 'user-emails'}
  - current_user.emails.each do |email|
    %li{id: dom_id(email)}
      = email.address
      - unless email.confirmed?
        %span.muted (unconfirmed)
      - if email.deleteable?
        = link_to "&times;".html_safe, remove_email_path(email.token), class: 'close email-remove', data: { behavior: 'confirm', confirm: "Are you sure you want to remove #{email.address} from your account?"}

= form_for current_user.emails.new do |form|
  %div.input-append
    = form.text_field :address, placeholder: 'Add another email'
    = form.button "Add", class: 'btn btn-primary'
%p
  = link_to "Edit", edit_me_path
  = link_to 'Log out', log_out_path, class: 'log-out'